services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./creation.sql:/docker-entrypoint-initdb.d/creation.sql
    networks:
      - agriflow-network
networks:
  agriflow-network:
    driver: bridge
